### ISSUE TITLE
Error: need class interface or enum

### ISSUE THREAD

**Issue by 201406042013** [acr31/features-javac#7]
Thank you very much for providing the code. I am having trouble using your code on a raw dataset from [[https://github.com/xing-hu/DeepCom](url)]. I am providing more details below:

1. The data format

The code snippet from the dataset is always a method or function and an example is shown below：

`public static String unEscapeString(String str,char escapeChar,char charToEscape){  return unEscapeString(str,escapeChar,new char[]{charToEscape});}`

2. The error messages:

 When I ran ` javac -cp extractor/target/features-javac-extractor-1.0.0-SNAPSHOT-jar-with-dependencies.jar -Xplugin:FeaturePlugin test.java `, 

the program throws the errors:

`test.java:1: Error: need class, interface or enum
public static String unEscapeString(String str,char escapeChar,char charToEscape){  return                                   
unEscapeString(str,escapeChar,new char[]{charToEscape});}
 `
`test.java:1: Error: need class, interface or enum
public static String unEscapeString(String str,char escapeChar,char charToEscape){  return unEscapeString(str,escapeChar,new char[]{charToEscape});}`

Would you mind providing some insights on how to adjust the data or source code? Thanks!

**Comment by acr31** [comment]
The feature extractor is a compiler plugin so you need to pass it Java code which compiles. It looks here like you are passing it a snippet of Java code rather than a full class definition.

As a general rule I would suggest making sure your program (test.java in your example above) compiles with javac normally before trying to use the feature extractor plugin. By this I mean that you should try:

`javac test.java`

and make sure that works without errors before trying the full command you mention above.

It might be the case for your data that its sufficient to wrap your snippets so that test.java contains:
`class test { <<INSERT SNIPPET> }`
